### PR TITLE
 Allows Entry Points of Specific modules to be customized/overridden

### PR DESCRIPTION
**Pull request by laxminarayan-uc**
Currently, Modules can have their own EntryPoints, but they cannot be customized. This patch fixes that.

### CODE REVIEW

**Comment by laxminarayan-uc** [comment]
Forgot to rebase

**Comment by yurikuzn** [comment]
Hi,

It's supposed that entry points of modules will be customized in Custom\EntryPoints\. Doesn't it work?

Customizing in \Custom\Modules\{ModuleName}\ is not supposed by design. I'm not willing to add such an ability w/o being totally sure that it's a really necessary feature.

**Comment by laxminarayan-uc** [comment]
Keeping EntryPoints of different modules in the same folder imposes these problems

1. That makes the directory structure inconsistent with the original directory structure.
1. To keep our Module customizations manageable, we have decided to keep the customizations of each module in seperate repositories. The lack of separation of EntryPoints for modules prevents us from having separate repositories, as they need to go into the same folder .
1. It also becomes an issue when dockerizing for development.  The code for the **customization** of different modules lives in different folders in the host machine and the volumes can be individually mounted to different module folders. Not allowing customization folders of individual modules to have their own EntryPoints folders prevents us from achieving this separation.

**Comment by yurikuzn** [comment]
1. We can't have it only for entry points. If for entry point then for everything else.
2. It's a quite serious change. So I need to think it out before implementing it.

**Comment by laxminarayan-uc** [comment]
Sounds good

**Comment by yurikuzn** [comment]
But I have 200+ items in my todo list, so this is not my high priority. I recommend using just \Custom\EntryPoints\ for now.

**Comment by laxminarayan-uc** [comment]
We can patch my commit before we use it. I was only sharing it with hopes that it will be useful for others.

**Pull request closed without merging**
