### PR TITLE
Add Thai Language Support

### PR DESCRIPTION
**Pull request by suparpat**

### CODE REVIEW

**Comment by yurikuzn** [comment]
Hi,

Thanks for PR. It's not good practice to mix different things in one PR. I mean changing gitignore and language files.

**Comment by suparpat** [comment]
I removed change on .gitignore file. Thanks.

**Comment by suparpat** [comment]
@yurikuzn Please review and let me know if any fix is required. Thank you!

**Comment by yurikuzn** [comment]
It looks OK.

**Pull request merged**
