### PR TITLE
Show account name in global search results

### PR DESCRIPTION
**Pull request by alasdaircr**
I suggested this years ago, but it wasn't chosen. Trying again :-)

Seems useful that with a large contact database, the global search displays not only the matching contact name but the account name too.

### CODE REVIEW

**Comment by yurikuzn** [comment]
Note: Module names should be formatted like "views/global-search/account-field" instead of "Views.GlobalSearch.AccountField" that is deprecated.

**Comment by alasdaircr** [comment]
@yurikuzn have pushed that change

**Comment by alasdaircr** [comment]
So shall I presume that this isn't needed?

**Comment by yurikuzn** [comment]
Not needed as it is now. Maybe we will improve it in more elegant way.

**Pull request closed without merging**
