### PR TITLE
Fix Multiline descriptions for Outlook.

### PR DESCRIPTION
**Pull request by Forestsoft-de**
Having trouble with new lines in Meeting description.

Only the first line shows in outlook.

New line should replaced by control by a control character \\n 

See https://social.technet.microsoft.com/Forums/lync/en-US/c16cc4aa-0a07-4742-929d-1b01d698066e/ics-file-description-with-colon-and-newline-is-displayed-without-newlines?forum=outlook

### CODE REVIEW

**Comment by yurikuzn** [comment]
Thanks

**Comment by yurikuzn** [comment]
Unit tests failed.

**Comment by Forestsoft-de** [comment]
Because the timestamp?

**Comment by yurikuzn** [comment]
Not apropriate phpunit version. And I tried to fix it failed due some other reason but I haven;t figured it out.

**Pull request merged**
