### PR TITLE
template wrapper name getter

### PR DESCRIPTION
**Pull request by eymen-elkum**
Hi,

I am working on new PDF engine, and I am almost finished (except for barcode), I just needed this core change,

### CODE REVIEW

**Comment by yurikuzn** [comment]
Hi,

Can you explain why internal template name is needed for PDF printing.

**Comment by eymen-elkum** [comment]
Sure,

The engine I used is not Pdf, but HTML, so I am displaying the result as html page

I need the template name as title of the page.

This was exciting experience to me, this way I can use the full power of css to make complex reports for clients

Soon later I will share more information about this extension

**Comment by eymen-elkum** [comment]
This is a screenshot:

Screen Shot 2021-07-30 at 4 59 39 PM

**Comment by yurikuzn** [comment]
I think we need to add a new field to template for Title rather than use existing Name.

**Comment by eymen-elkum** [comment]
The name field is already used for PDF file name, adding a new field may not needed, I followed the same convension
But still good idea, so the function will return the name if the title is empty

**Comment by eymen-elkum** [comment]
sometimes clients would like to append the printed entity name to the pdf file name.

**Comment by yurikuzn** [comment]
Added title: https://github.com/espocrm/espocrm/commit/a56acf553c2f8b28ec74dbef3b34b105ed055841

I will think about supporting placeholders in title later.

**Comment by yurikuzn** [comment]
Are you implementing headless chrome for PDF printing?

**Comment by eymen-elkum** [comment]
> Are you implementing headless chrome for PDF printing?
To be honest, some features not implemented yet like repeating header every page, I may make this extension open source, then community can help.

**Comment by yurikuzn** [comment]
FYI. I added `getStream` method to Contents interface to be able to work with large files (not actual for Tcpdf).

**Comment by eymen-elkum** [comment]
Thank you so much for the information, I will check it!

**Pull request closed without merging**
