### PR TITLE
allow custom view for portal navbar

### PR DESCRIPTION
**Pull request by eymen-elkum**
Hi @yurikuzn please check this, best regards.

### CODE REVIEW

**Comment by yurikuzn** [comment]
I recommend to check in your custom navbar:

```
this.getUser().isPortal()
```

**Comment by eymen-elkum** [comment]
You are right, but we need to include the custom script in the default portan-navbar view for better safe upgrade, as you may add more code to the portal-navbar view in the future.

I think if espocrm need different views for portal and main
then the extension must follow the same logic.

**Comment by eymen-elkum** [comment]
thank you ...

**Comment by yurikuzn** [comment]
Thanks for fix.

**Pull request merged**
