### PR TITLE
admin ACL for clientDefs.json schema

### PR DESCRIPTION
**Pull request by Kharg**
add Admin ACL for clientDefs, I don't know if it's supported anywhere else apart from buttons and dropdowns, it would be nice to have it where it's supported so when using Schema it doesn't show the parameter as wrong.

### CODE REVIEW

**Comment by yurikuzn** [comment]
There's no such an option.

**Comment by yurikuzn** [comment]
Use *accessDataList* for admin check.

**Comment by Kharg** [comment]
Thank you. It must have been a false memory.

Is that how the advanced pack does it for buttons? Using accessDataList when you select admin?

**Comment by yurikuzn** [comment]
I don't remember. Maybe. It's also possible to use a handler to control visibility.

**Pull request closed without merging**
