### PR TITLE
fix: override login view from config

### PR DESCRIPTION
**Pull request by ayman-alkom**
It is a nice feature to be able to override the login view, and it is already has been implemented,
but the problem is that metadata will not initialized before the login,
I hope to accept this change

### CODE REVIEW

**Comment by ayman-alkom** [comment]
I hope you having a very nice holiday :)

**Comment by yurikuzn** [comment]
Sorry, no.

**Comment by ayman-alkom** [comment]
sorry to know that, and sorry because you not clearing why not

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/4dc08dd37c12b8db6ae79cb89acfc9c1ffd0a09d

**Comment by ayman-alkom** [comment]
thanks

**Pull request closed without merging**
