### PR TITLE
Fixed model seed cache

### PR DESCRIPTION
**Pull request by mozkomor05**

### CODE REVIEW

**Comment by yurikuzn** [comment]
This code never worked since the beginning, accepting in the fix release w/o a lot of testing is not an option. I was about to accept it.

**Comment by mozkomor05** [comment]
> This code never worked since the beginning, accepting in the fix release w/o a lot of testing is not an option. I was about to accept it.

I don't get it. Is the fix wrong or should I PR into master?

**Comment by yurikuzn** [comment]
It can really cause a lot of issues. I was so tired, so could accept it. luckely I didn't.

**Comment by yurikuzn** [comment]
I see that it potentially could cause a lot of bugs.

**Comment by mozkomor05** [comment]
Sure. I get it. Never commit untested (even if it was **_dead code_** previously) code to `fix`. So should I create PR to `master`?

**Pull request closed without merging**
