### PR TITLE
list record: enable top bar  if "display total count" is true

### PR DESCRIPTION
**Pull request by ayman-alkom**
I hope this change to be accepted as the normal users are not able to see the totals even it is enabled in the config

Best Regards

### CODE REVIEW

**Comment by yurikuzn** [comment]
Won't this show top bar in places where it's not supposed to be shown? Like relationship panels, dashlets?

**Comment by ayman-alkom** [comment]
if `displayTotalCount = false` then this change will not affect anything
as I noticed the value is false in the relationship so the effect only will be in the main lists
also I think that this condition is needed as the top bar already include this piece of code (total)

**Comment by ayman-alkom** [comment]
In fact I am not sure about this, may need test

**Comment by yurikuzn** [comment]
Yes. It changes every list in the system. Please, don't rely only on me testing PR.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/0721bd5c27550bd8863696edba5a235e5e2bfd30

**Comment by ayman-alkom** [comment]
As I see you only made like a code clean & format, so the problem still exist.
I don't want to make this change privately, and instead I can improve the PR so the list will have another parameter `forceHideTotalCount` so that can be overridden in the dashlets

**Comment by yurikuzn** [comment]
There a multiple places other than dashlets. `forceHideTotalCount` is not fine for us.

**Pull request closed without merging**
