### PR TITLE
Fix template markup

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**

### CODE REVIEW

**Comment by yurikuzn** [comment]
I applied the fix to the *fix* branch. https://github.com/espocrm/espocrm/commit/7d507460be902ec387758a818dcb24ad86bb06af

**Comment by yurikuzn** [comment]
BTW. How did you notice the problem?

**Comment by tim-bezhashvyly** [comment]
The problem is not manifesting itself during rendering. I saw it in my IDE.

**Comment by tim-bezhashvyly** [comment]
BTW I would appreciate if you will give me a hint how to override this template.

**Comment by yurikuzn** [comment]
You can monkey patch the class from `views/site/header.js`.

**Pull request closed without merging**
