### PR TITLE
afterRemove hook didn't remove all notes, leading to 404s and blank e…

### PR DESCRIPTION
**Pull request by alasdaircr**
…ntity names

### CODE REVIEW

**Comment by yurikuzn** [comment]
I think we need to opt to setting deleted = 1 instead of removing here.

**Comment by alasdaircr** [comment]
Sure - then eventually could be undo'd which would be great. I'll change this soon

**Comment by yurikuzn** [comment]
I'm concerning about next. Note related to opportunity through parent and related to account through superParent. If we remove account we will lost notes of opportunity.

**Comment by yurikuzn** [comment]
I've just remembered that that was a reason why I didn't make deleting by super parent.

**Comment by alasdaircr** [comment]
I see. A MUCH better option :-) would be to handle the deleted entities and show them in the notes, but as strikethrough.

And a note should be left for deletions with the same strikethrough effect on the entity name.

Also, any deleted entity should not be clickable as the 404 page is not that helpful for people who don't understand what a 404 is...

**Comment by alasdaircr** [comment]
e.g.

**John** mentioned you in relation to **Contact** ~~Brian Gone~~

**Comment by alasdaircr** [comment]
closing this then as it turned into more of a feature request - fixing notes to deleted entites

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/245

**Pull request closed without merging**
