### PR TITLE
fix: Date field 'before' and 'after' validations 

### PR DESCRIPTION
**Pull request by kaminarifox**

### CODE REVIEW

**Comment by yurikuzn** [comment]
It breaks an existing functionality.

**Comment by kaminarifox** [comment]
> It breaks an existing functionality.

At this moment before/after validators not working at all. Is there a proper way to fix it?

**Comment by yurikuzn** [comment]
They are working. Try creating meeting with date end before date start and you will get an invalid message.

**Comment by kaminarifox** [comment]
Meeting use the _datetime-optional_ field, but i talk about the _date_ field in custom entities

**Comment by yurikuzn** [comment]
It works for date field as well.

**Comment by kaminarifox** [comment]
In the validator `otherValue` always undefined, because `field` is just date string

https://github.com/espocrm/espocrm/blob/d02529ee86b84c150fec6a86c4ac5be2d90bc611/client/src/views/fields/date.js#L329

**Comment by yurikuzn** [comment]
I think you misunderstand how this validation supposed to work.

**Comment by kaminarifox** [comment]
Oh, now i see. Sorry for wasted time.

Have you thought about adding a validator depended on date string or making current validators more universal?

**Comment by yurikuzn** [comment]
Yes. I have this in my TODO list.

**Pull request closed without merging**
