### PR TITLE
Fix utf-8 csv export to excel

### PR DESCRIPTION
**Pull request by olexus**

### CODE REVIEW

**Comment by grzegorzgie** [comment]
The fact is not working properly. Also I have a problem in Polish.

**Comment by yurikuzn** [comment]
Is it not working with this fix applied?

**Comment by grzegorzgie** [comment]
Unfortunately, the latest version , which checked the export did not work properly . When was the amendment ?

**Comment by yurikuzn** [comment]
No enough information about the issue. Tabulation lacks of one space.

**Pull request closed without merging**
