### PR TITLE
Fix #567: Add custom config override

### LINKED ISSUE #567: Add environment-specific configuration overriding defaults in global configuration and ignored by git
## Problem
There is no way to have global configuration with reasonable defaults (which is versioned by git) - together with environment-specific tweaks (which are ignored by git).

## Reason
For now we do not have a mechanism of including (if exists) environment configuration, which overrides global values.

## Solution
We should adapt something similar to [what Yii currently has](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/structure-environments.md).

### PR DESCRIPTION
**Pull request by PatchRanger**
### Problem
See #567.

### Solution
Just add a way to override global configuration by adding a `data/customConfig.php` file.
It solves a problem of having different environment-specific settings: each environment just could have its own `data/customConfig.php` file, basing on common `data/config.php` as reasonable defaults.
Also it could serve as little step toward #446.

### CODE REVIEW

**Comment by yurikuzn** [comment]
Hi,

What is the benefit of having customConfig.php with config.php being in gitignore?

**Comment by yurikuzn** [comment]
Configuration changed through UI will be written in config.php that can be overriden by customConfig.php. So Admim user won't be able to change some parameters.

**Comment by yurikuzn** [comment]
I think properly would be to add defaultConfig.php (verisioned by git) loading before existing config.php.

**Comment by PatchRanger** [comment]
> What is the benefit of having customConfig.php with config.php being in gitignore?
`customConfig.php` should be moved into the correct place during the process of deployment.

> Configuration changed through UI will be written in config.php that can be overriden by customConfig.php. So Admin user won't be able to change some parameters.

That's true. It's a downside of this MR, I agree. Though I don't think there is a huge desire to change DB settings through UI after successful installation. While introducing such change would allow to have different settings for different environments - which is very useful for Continuous Integration.

> I think properly would be to add defaultConfig.php (verisioned by git) loading before existing config.php.

That's an interesting approach. Should we include it by `loadConfig` - or just `require` (if it exists, of course) directly in `config.php`?

**Comment by yurikuzn** [comment]
Including defaultConfig.php file in config.php is a simplest way. I like it.

**Comment by PatchRanger** [comment]
@yurikuzn I found that it's not that easy to just add `include` into the `config.php`. As `config.php` gets rebuilded - the correct place to introduce the change is `Config::save()`. But it's not enough to just add `include 'defaultConfig.php';` above the settings - we need to get the content of that file and merge it with current.
So I decided to just modify the previous implementation: now it considers custom configuration as default settings - not overrides. I guess, it should fit.

**Comment by PatchRanger** [comment]
@yurikuzn Could you please review the proposed changes?

**Pull request closed without merging**
