### PR TITLE
Added CORS support to the API

### PR DESCRIPTION
**Pull request by bandtank**
Many clients require CORS support, which the current API does not support. This change adds CORS support through optional configuration parameters. If enabled, the API will respond with CORS-specific headers and information, which clients often need. One example of this is Microsoft Teams; if the `OPTIONS` header is not properly handled, integration with Microsoft Teams will not work.

To enable CORS support, four new configuration keys need to be added:
```
  'apiEnableCORS' => true,
  'apiCORSOrigins' => [
    0 => 'https://some.site.com'
  ],
  'apiCORSCacheMaxAge' => 86400,
  'apiCORSAllowedMethods' => [
    0 => 'GET',
    1 => 'POST',
    2 => 'DELETE',
    3 => 'PATCH',
    4 => 'PUT',
    5 => 'OPTIONS'
  ],
  'apiCORSAllowedHeaders' => [
    0 => 'Content-Type',
    1 => 'Accept',
    2 => 'Custom-Key'
  ],
```

Allowable CORS origins should be added to `apiCORSOirigins` and allowable headers should be added to `APICORSAllowedHeaders`. In the example, requests from `https://some.site.com` will be accepted and requests with a type of `OPTIONS` will respond by allowing `Content-Type`, `Accept`, and `Custom-Key` headers.

This has been tested for years in my custom installation of EspoCRM by continually modifying `Starter.php` after each update.

### CODE REVIEW

**Comment by bandtank** [comment]
This is similar to #1046, #141 (an issue I responded to a long time ago), and #473 (another issue I responded to a long time ago). Solving the problem with Apache does not work in every case and it is more complex. This PR solves the problem in a scalable and flexible way.

**Comment by yurikuzn** [comment]
I'm not able to look into for the next few weeks due extreme load with very important work. This PR can't accepted as it does not meet our requirements (header, server usage, not via classes). I will be able to look into in about a month.

**Comment by bandtank** [comment]
Ok, I understand. I don't know what to change for the code to meet your requirements. If you have time to add details, I will make the required changes. Otherwise, I'll respond to any questions you have in a month when you have time to review the code.

**Comment by yurikuzn** [comment]
To answer how exactly it can be done, I need to investigate, but I have no time. This quite important feature that needs investment to design it properly.

**Comment by bandtank** [comment]
I agree. I will make a few changes to match your request, but I understand it will take time and a lot of testing.

**Comment by yurikuzn** [comment]
I think the Middleware framework would fit the best  https://docs.espocrm.com/development/metadata/app-api/#app-api. But I can't tell for sure.

**Comment by yurikuzn** [comment]
I create a PR https://github.com/espocrm/espocrm/pull/2754/files

**Pull request closed without merging**
