### PR TITLE
pdf template custom page size.

### PR DESCRIPTION
**Pull request by ayman-alkom**
the same pr but to different branch

### CODE REVIEW

**Comment by yurikuzn** [comment]
Thanks.

**Comment by yurikuzn** [comment]
Do we need pageOrientation field for Custom size? I think we can hide it.

**Comment by ayman-alkom** [comment]
the current behavior respect the value of pageOrientation so that if you replaced between the pageWidth & pageHeight value you will get the same result
if we removed the pageOrientation then the value orientation must be calculated (may read only better than hidden)

**Comment by yurikuzn** [comment]
Should we support decimal numbers (float) for size?

**Comment by yurikuzn** [comment]
I think yes. TCPDF must support it.

**Comment by yurikuzn** [comment]
Also I need to make size fields required if custom is selected.

**Comment by ayman-alkom** [comment]
you are right, I can do them

**Comment by ayman-alkom** [comment]
also the width must be larger than the (left + right margins + 1), the same for height

**Comment by ayman-alkom** [comment]
> Should we support decimal numbers (float) for size?
we can also keep the integer and refer to it as mm instead of cm, the we will update the pdf service to remove `* 10` as well

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/97a572cf966408ca80297935e71cab107e3cf573

**Pull request merged**
