### PR TITLE
Fix clear cache typo update fr lang

### PR DESCRIPTION
**Pull request by sebdoido**
2 commits

Update
client/res/templates/clear-cache.tpl 
client/src/views/clear-cache.js      
to fix typo

+ update fr_FR lang

### CODE REVIEW

**Comment by yurikuzn** [comment]
Thanks

**Comment by yurikuzn** [comment]
Target.json is not needed. It has been removed from repository.

**Comment by sebdoido** [comment]
Ok, i think we should update the POEditor records because it has been generated after i downloaded the latest .po file

**Comment by yurikuzn** [comment]
I have just done it.

**Comment by sebdoido** [comment]
Thanks :)

**Pull request merged**
