### PR TITLE
css fix

### PR DESCRIPTION
**Pull request by mozkomor05**
When 25% < 80px, the currency field overflows. Since table-cells don't support min-width (min and max widths have undefined behaviour on tables since CSS 2.1), this can be resolved in one of two following ways:
- Remove the table layout and style the inputs using inline-block.
- Change table layout to `auto` and let the browser fix the overflowing width.

image

### CODE REVIEW

**Comment by yurikuzn** [comment]
Auto causes the issue:

image

**Comment by yurikuzn** [comment]
Might need to remove
```
.selectize-input {
    min-width: 80px;
}
```

**Comment by mozkomor05** [comment]
Does the `auto` issue apply to currency field?

**Comment by yurikuzn** [comment]
Fixing it only for currency is not the way to go. The same issue is for all input-group fields having selectbox.

**Comment by mozkomor05** [comment]
I also noticed that select boxes don't work inside `.table>tbody>tr>td` as the dropdown gets cutted by `overflow:hidden`.

**Comment by mozkomor05** [comment]
> I also noticed that select boxes don't work inside `.list>table td` as the dropdown gets cutted by `overflow:hidden`.

That might actually be irrelevant. Maybe I should not put the fields inside the container with `list` class.

**Comment by yurikuzn** [comment]
Bad. Need to find a solution. Selectbox already took me more than 30h of work.

**Comment by yurikuzn** [comment]
Does it work in cases like on your screenshot in the first post?

**Comment by mozkomor05** [comment]
The select box? No it doesn't, it cuts the content of the dropdown. But that might be my fault, since I render the field inside a table which is inside a container with the `list` class. Maybe I should modify my custom view to use different class and copy the styles I need.

**Comment by yurikuzn** [comment]
I though it's the Quote items field from the Sales Pack.

For dropdowns on the right on the list we have overflow: visible as an exclusion. Also whoever customized list view to be editable will have the issue.

**Comment by mozkomor05** [comment]
As far as I know, there's no way an edit-mode field can get inside a `record/list` view (with `list` class) in native Espo.

**Comment by mozkomor05** [comment]
Yes. So the issue with `overflow:hidden` is my fault. 

There's still the issue when 25% of the width of the field is less than 80px.

**Comment by yurikuzn** [comment]
I will remove 80px min width limitation that will fix the issue.

**Pull request closed without merging**
