### PR TITLE
Translate es

### PR DESCRIPTION
**Pull request by PanuWeb**
es_ES - Improvements. New translations.

### CODE REVIEW

**Comment by yurikuzn** [comment]
Thanx

**Comment by PanuWeb** [comment]
Did you see the comment that I left on the other pull request?

**Comment by yurikuzn** [comment]
Yes

**Comment by PanuWeb** [comment]
I was referring to [this](https://github.com/espocrm/espocrm/pull/356#issuecomment-271260078):
> Sorry, but I do not understand: your commits a53ccb6 and e5e082c, do not make the same changes as my commit 0fceacf?

Could you tell me why this happens? Thank you!

**Comment by yurikuzn** [comment]
I can say that's all is fine. Nothing to worry about.

**Comment by yurikuzn** [comment]
Permissions were wrong due some reason.

**Comment by PanuWeb** [comment]
+1

**Pull request merged**
