### PR TITLE
Fix issue #2009

### PR DESCRIPTION
**Pull request by HungNguyenPTN**
-Fix loadAdditionalFields does not work for email templates
-Similar to PDF template
This fix for issue [#2009 ](https://github.com/espocrm/espocrm/issues/2009)

### CODE REVIEW

**Comment by yurikuzn** [comment]
Hi,

Thanks for PR. But it has an issue. The code should be inserted inside the `if` block.

**Comment by HungNguyenPTN** [comment]
Hi, i updated.
inside `if (parent)` right?
thank you for responed

**Comment by yurikuzn** [comment]
Looks right.

**Review by boydle — COMMENTED** [review]
Hi, I think the 2 new lines of code should have been added at line 121 not where they are. With this code I think the loadAdditionalFields could be missed when $params['parent'] is set.

**Comment by HungNguyenPTN** [comment]
Hi, i think @boydle  comment is more correct. But i cant edit anymore. How can i fix this

**Comment by yurikuzn** [comment]
I'd leave as it is. The place where 'parent' is set should care about populating all fields I think. The less object mutation inside a service the better I believe.

**Pull request merged**
