### PR TITLE
add proxy support in Upgrade.php

### PR DESCRIPTION
**Pull request by hi-ko**
I didn't find a way to use a http proxy for command upgrade so I added proxy support in application/Espo/Core/Console/Commands/Upgrade.php

### CODE REVIEW

**Comment by yurikuzn** [comment]
Such changes are extremely risky would require a lot of testing. In the future we need to come up some generic solution.

**Comment by yurikuzn** [comment]
JFI, you can also upgrade manually, but downloading an upgrade package from the webstite.

**Comment by hi-ko** [comment]
Why is adding proxy support in downloadFile / getVersionInfo per se risky? I would assume the other way around: upgrade should not be run without a proxy from a server ;-)
Maybe the whole Upgrade should not be owned and run by the runtime user (e.g. www-data) but that's another story ...

**Comment by yurikuzn** [comment]
Any change in upgrade is risky that requires our QA to engage. If upgrade fails for some users, we have a huge headache. 

Adding new config parameters is the process that can't reverted. We also add all new parameters to docs. If we add these parameters for upgrade we would also need to support them in any CURL usage. We need some generic framework. We need to choose good names for such parameter either.

**Comment by yurikuzn** [comment]
> upgrade should not be run without a proxy from a server

What do you mean?

**Comment by hi-ko** [comment]
A web server should not have direct access to the internet. Best practice for security is to use a http proxy and monitor / whitelist urls. Similar how this is done with apt on debian/ubuntu.

> Any change in upgrade is risky that requires our QA to engage. If upgrade fails for some users, we have a huge headache.
So you mean I should create a feature issue instead, so your team can cover all the required steps?

**Comment by yurikuzn** [comment]
We need a generic solution for all CURL usages. I added it to our backlog.

**Comment by hi-ko** [comment]
good point! I already tried that but may have lost the env variables using sudo.

The way it works without the need to add the parameters to `/etc/profile`:
```
export http_proxy='http://1.2.3.4:8888'
export https_proxy=$http_proxy
sudo -E -u www-data php /var/www/html/espocrm/command.php upgrade
```

**Comment by hi-ko** [comment]
or even a bullet proof fix would be to create a simple wrapper to be owned and run as root:

```
# cat ~/bin/esporcrm-command
export http_proxy='USERNAME:PASSWORD@PROXYIP:PROXYPORT'
export https_proxy=$http_proxy
export no_proxy='*.mycompany.com *.mycompany.local'
sudo -E -u www-data php /var/www/html/espocrm/command.php $@
```
```
# ~/bin/esporcrm-command upgrade
There are no available upgrades.
```

**Comment by yurikuzn** [comment]
BTW upgrade is OK to run under root user.

**Comment by yurikuzn** [comment]
When running under root, upgrade script applies *chown* for necessary files.

**Pull request closed without merging**
