### PR TITLE
Upgrade glob to version 11.x

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**
Resolves `cross-spawn` vulnerabilities

### CODE REVIEW

**Comment by yurikuzn** [comment]
Hi Tim,

Could you please apply our CLA by making a commit in the (CLA repository](https://github.com/espocrm/cla)? It's simple to do.

**Comment by yurikuzn** [comment]
I see that glob 11 requires node 20 which is only ~1 year old.

**Comment by tim-bezhashvyly** [comment]
> Hi Tim,
> 
> Could you please apply our CLA by making a commit in the (CLA repository](https://github.com/espocrm/cla)? It's simple to do.

Done

**Comment by yurikuzn** [comment]
I can see that we have already cross-spawn 7.0.6 which appears to be fixed. https://github.com/espocrm/espocrm/pull/3214

Might be not relevant anymore.

**Comment by tim-bezhashvyly** [comment]
> I see that glob 11 requires node 20 which is only ~1 year old.

What's the minimum EspoCRM Node requirement?

**Comment by yurikuzn** [comment]
> What's the minimum EspoCRM Node requirement?

15

```
  "engines": {
    "npm": ">=7",
    "node": ">=15"
  }
```

**Comment by tim-bezhashvyly** [comment]
Sorry. Please excuse the hassle. I'm closing the PR.

**Comment by yurikuzn** [comment]
No problem )

**Pull request closed without merging**
