### PR TITLE
es_ES - Update translations to today

### PR DESCRIPTION
**Pull request by PanuWeb**
Updated translations. Several improvements were introduced.

If you are a Spanish speaker and you have doubts about the criteria used in the translation I recommend that you follow this thread: [http://forum.espocrm.com/forum/developer-help/23656-translate-es-notes-for-translators-who-want-to-translate-to-spanish](http://forum.espocrm.com/forum/developer-help/23656-translate-es-notes-for-translators-who-want-to-translate-to-spanish)

### CODE REVIEW

**Comment by yurikuzn** [comment]
Thanks a lot

**Comment by PanuWeb** [comment]
You're welcome. Happy weekend.

**Comment by yurikuzn** [comment]
We have to revert pull request. You commited exess files with changed file permissions.

**Comment by yurikuzn** [comment]
I should have been more careful while reviewing. That could give us a hard time. Please add only relevant files to commits.

**Comment by PanuWeb** [comment]
I am so sorry. I change the permissions. I thought I was "reversing the changes" made by me :cry:.

How can I solve the problem?

**Comment by yurikuzn** [comment]
You can make one more pull request without commit that changes permissions.

**Comment by yurikuzn** [comment]
I will do it by myself.

**Comment by PanuWeb** [comment]
I've arrived late

**Comment by PanuWeb** [comment]
Sorry, but I do not understand: your commits [a53ccb6](https://github.com/espocrm/espocrm/commit/a53ccb66c5eeb43464e1fa5c397f4820711502f9) and [e5e082c](https://github.com/espocrm/espocrm/commit/e5e082c48b9ff0264db8f4060d59c50b2b42b4a7), do not make the same changes as my commit [0fceacf](https://github.com/PanuWeb/espocrm/commit/0fceacf148fab4d5e62af30a9e7b92dc00067191)?

**Pull request merged**
