### PR TITLE
Filters for date and datetime to search by week

### PR DESCRIPTION
**Pull request by bandtank**
This request adds a few filters to date and datetime fields:
* Current Week - search for records within the current week (based on the user's weekStart preference or the system's weekStart setting if the user does not have a preference)
* Last Week - Look for records in the last full week (the current week is not searched)
* Last X Weeks - Look for records in the last X full weeks (the current week is not searched)
* Next Week - Look for records in the next full week (the current week is not searched)
* Next X Weeks - Look for records in the next X full weeks (the current week is not searched)

Many businesses operate on a weekly basis, which makes searching, reporting, and filtering records with weekly filters very attractive. I currently build these filters into my instances manually. Instead of continuing to do that, I took the time to add the features to the application in a (hopefully) maintainable way.

If you do not like this feature or some of the changes, please let me know if there is anything I could change for it to be accepted. Otherwise, I will probably release the features as an extension, presuming I can figure how to do that.

image

image

### CODE REVIEW

**Comment by bandtank** [comment]
#2284

**Comment by yurikuzn** [comment]
Hi,

This raise some design issues. It was supposed that the Converter class is user agnostic. I'll consider this enhancement when get a chance, maybe will re-implement, not sure.

To add filters in a module:

* Define custom where item converters: https://docs.espocrm.com/development/metadata/app-select/#whereitemconverterclassnamemap
* Use monkey patching to add additional search types for date field view: https://forum.espocrm.com/forum/developer-help/100485-how-to-add-javascript-code
* For DateTimeTranformer, it may be trickier.

**Comment by bandtank** [comment]
Ok, sounds good. I thought about adding the feature in a module, but I couldn't figure out how to work around DateTimeTranformer. I'll see if I can figure something out. Thanks

**Comment by yurikuzn** [comment]
See https://github.com/espocrm/espocrm/blob/8.1.1/application/Espo/Core/Select/Where/ConverterFactory.php#L150. As an option, you can have this filters only for date view.

**Comment by yurikuzn** [comment]
You can also by pass the date-time transformer and rely only on where item converter for both date-times and dates. I think this would be the easiest and future-proof.

**Comment by bandtank** [comment]
I am closing this for now because the commits are causing too much noise. I will reopen the PR when the work is done and ready to be reviewed. Hopefully the new approach works betters.

**Pull request closed without merging**
