### PR TITLE
improved CommandManager customization surface

### PR DESCRIPTION
**Pull request by beppe9000**
is this ok? please provide feedback

### CODE REVIEW

**Comment by yurikuzn** [comment]
I see no reason for this changes. CommandManager is not supposed to be extended.

**Comment by yurikuzn** [comment]
I can afford changes in such critical places. This is not covered with tests well. Risk to break upgrading for example, that will be a disaster.

**Comment by beppe9000** [comment]
I shall revisit this once command handling is more mature

**Comment by yurikuzn** [comment]
It's already fine. If you want something very very custom -- just create a separate php file.

**Comment by beppe9000** [comment]
You mean by overriding the `consoleCommandManager` loader in `/custom`  and returning a different class?

**Pull request closed without merging**
