### PR TITLE
Fix pl_PL

### PR DESCRIPTION
**Pull request by grzegorzgie**
Repair linguistic errors

### CODE REVIEW

**Comment by grzegorzgie** [comment]
I do not understand this software . Where can I see a log of the proposed changes? I would like to improve the translation of the Polish language in the entire system because it is very vain .

**Comment by yurikuzn** [comment]
We can accept pull request only if contributor accepts our CLA https://github.com/espocrm/cla

Log of proposed changes is in issues and on the forum in feature requests section.

**Comment by grzegorzgie** [comment]
Funny . So I accept this agreement , I would like to develop EspoCRM in the Polish language version. Where can I give private message to you? I'd like to apologize , bitterness is a bad counselor .

**Comment by yurikuzn** [comment]
Private messages are available on our forum.

**Pull request merged**
