### PR TITLE
Duplicate: re-create related links instead of just update the relation

### PR DESCRIPTION
**Pull request by ayman-alkom**
Hi @yurikuzn 
In my project this change was very important, and I hope you accept it.
If you want we may add a boolean member variable to the record service that enable or disable the re-creation

### CODE REVIEW

**Comment by ayman-alkom** [comment]
Hi yuri
any feedback for this

**Comment by yurikuzn** [comment]
Hi Ayman,

I don't think we need to have this feature. It's possible to come up with a lot of interesting features that would be needed for some, but it all inflates codebase.

**Comment by rodrigoscoelho** [comment]
Just asking, please don't badly understand me. Is espocrm based on an open
community? Or it is a closed app with some code open to allow users to fork
and create their own versions?

I'm not a programmer, and I'm not experienced on this, so, forgive me if
I'm asking something obvious.

Anyway, it's a good piece of code....



Em 6 de set de 2017 14:59, "Yuri Kuznetsov" <notifications@github.com>
escreveu:

**Comment by yurikuzn** [comment]
It's open source. GPLv3. You can fork an entire application.

Some additional extensions like advanced pack are not under GPLv3. They have their own licenses and you not able to redistribute.

**Comment by ayman-alkom** [comment]
sometimes I feel the same as @rodrigoscoelho do, I feel like this app is not community driven project, and in the same time I understand your opinion that some features may reduce the code safety.
I feel that some feature like this is strongly wanted, and easy to be done.
any way you can can close this PR, I can keep it in my own project only.

**Pull request closed without merging**
