### PR TITLE
Fix #585: Verbose JSON::decode()

### LINKED ISSUE #585: Json::decode():unexpected character
### Problem
I keep receiving such messages into the EspoCRM logs:
```
[2017-07-07 01:07:13] Espo.ERROR: Json::decode():unexpected character [] []
```
There's for sure some issue with JSON-encoding in my installation of EspoCRM - but the error message doesn't give a chance to understand where.

### Proposal
Let's make this error more verbose.

### PR DESCRIPTION
**Pull request by PatchRanger**
### Solution
Taking `JSON::encode()` as a basement and an example, added the value, that breaks JSON-decoding, to the log message.

### CODE REVIEW

**Comment by yurikuzn** [comment]
Hi,

This might make log files very large.

**Comment by PatchRanger** [comment]
@yurikuzn I agree, but it will make it possible to fix it. Otherwise we have no chance)

**Comment by PatchRanger** [comment]
@yurikuzn `JSON::encode()` does the same thing - it logs `$json` variable in case of fail. I guess, it's required to (possibly) crowd logs in order to notify about the cause of the trouble.

**Comment by yurikuzn** [comment]
I think we could cut the print to the certain number of characters.

**Comment by PatchRanger** [comment]
@yurikuzn I've enabled "Allow edits from maintainers" option - could you please add cutting to the certain number of characters the way you consider appropriate & merge the PR?

**Comment by PatchRanger** [comment]
@yurikuzn I've added cutting to 255 characters, please review.

**Pull request closed without merging**
