### PR TITLE
fix convert lead map fields

### PR DESCRIPTION
**Pull request by eymen-elkum**
When tried to use the convert fields map feature I faced this issue and fixed it.
Not sure if I have to pull to master or fix branches, you can edit the PR to change the target branch

photo_2023-01-20 3 07 57 PM

### CODE REVIEW

**Comment by yurikuzn** [comment]
More detail input about the issue with PRs is needed.

**Comment by eymen-elkum** [comment]
In the [line](https://github.com/espocrm/espocrm/pull/2574/files#diff-f434b574881b17f581334c17a2df2149eb71bebe28c30d82838342db5c6a578cR404) we need type of field on the target scope (ex: RealEstateproperty) but it search in Lead scope, so the type  is empty always unless the same field is exist on both entities.

**Comment by yurikuzn** [comment]
It's clear now. Thanks for explanation.

**Comment by yurikuzn** [comment]
On your screenshot, there are currency fields. They were not affected by the bug, right?

**Comment by eymen-elkum** [comment]
Not affected

**Pull request merged**
