### PR TITLE
Use common English salutations

### PR DESCRIPTION
**Pull request by alasdaircr**
Ms. and Miss are common british salutations, Drs. is not so common

### CODE REVIEW

**Comment by alasdaircr** [comment]
Were you not interested in this?

**Comment by yurikuzn** [comment]
The existing list is enough we think. Users can manage the list in Field Manager.

**Comment by alcoheca** [comment]
Well in terms of the English language, Mr, Ms, Miss and Mrs are all primary and should be there. The rest is just superfluous.

Drs. doesn't exist in English (if you mean female doctor)

**Comment by yurikuzn** [comment]
You're right about Drs. I think we need to add Prof. but Miss is unnecessary.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/1c7785f6ba5bd9e5c1e939b36280c17a0e3e3b3d

**Comment by alasdaircr** [comment]
Some women still use Miss instead of Ms, but this is a step in the right direction. thanks

**Pull request closed without merging**
