### PR TITLE
image field: add maximum size option

### PR DESCRIPTION
**Pull request by ayman-alkom**
the last commit in not important

### CODE REVIEW

**Comment by yurikuzn** [comment]
There are some finesses we must add to this feature. Like, server-side validation. https://github.com/espocrm/espocrm/issues/670

**Comment by ayman-alkom** [comment]
okey, I will add this

**Comment by yurikuzn** [comment]
No need. I can do it by myself. There are some nuances making this not very easy to implement.

**Comment by ayman-alkom** [comment]
okey you know very well what is more fit to be done.
I don't know if you will apply this PR then make that fineness, or you will make all the changes in separate commits.
just close this PR if you dont need it or tall me what to change if you want to merge it.

**Pull request closed without merging**
