### PR TITLE
CORS middleware

### LINKED ISSUE #2755: CORS middleware
Middleware class: `Espo\Tools\Api\Cors\Middleware`. Can be [added](https://docs.espocrm.com/development/metadata/app-api) to the global list or to specific routes or controllers. 

Config example:

```
'apiCorsAllowedOriginList' => ['myhost.com'],
'apiCorsAllowedMethodList' => ['POST',  'PUT'],
'apiCorsAllowedHeaderList' => [
  'Content-Type',
  'Accept',
  'X-Api-Key'
]
```

### PR DESCRIPTION
**Pull request by yurikuzn**
Middleware class: `Espo\Tools\Api\Cors\Middleware`. Can be [added](https://docs.espocrm.com/development/metadata/app-api) to the global list or to specific routes. 

If added to the global list, you also need to add [routes](https://docs.espocrm.com/development/api-action/).

Routes example:

```json
[
    {
        "route": "/:controller/:id",
        "method": "options"
    },
    {
        "route": "/:controller",
        "method": "options"
    }
]
```

Config example:

```
'apiCorsAllowedOriginList' => ['https://myhost.com'],
'apiCorsAllowedMethodList' => ['POST',  'PUT'],
'apiCorsAllowedHeaderList' => [
  'Content-Type',
  'Accept',
  'X-Api-Key'
]
```

### CODE REVIEW

**Comment by bandtank** [comment]
Thanks for writing this so quickly. It looks like a great solution.

I copied the files into my environment to test the new feature. I'm not sure what is wrong, but it doesn't seem to be working yet.

`custom/Espo/Custom/Resources/metadata/app/api.json`:
```
{
  "globalMiddlewareClassNameList": [
      "Espo\\Tools\\Api\\Cors\\Middleware"
  ]
}
```

`data/config.php`:
```
  'apiCorsAllowedOriginList' => [
    0 => 'https://comet.odysseypediatric.com'
  ],
  'apiCorsAllowedMethodList' => [
    0 => 'GET',
    1 => 'POST',
    2 => 'DELETE',
    3 => 'PATCH',
    4 => 'PUT',
    5 => 'OPTIONS'
  ],
  'apiCorsAllowedHeaderList' => [
    0 => 'Content-Type',
    1 => 'Accept',
    2 => 'X-Api-Key'
  ],
```

The new files:
image

In `application/Espo/Core/Api/Starter.php`:
```
    private function addGlobalMiddlewares(SlimApp $slim): void
    {
        foreach ($this->middlewareProvider->getGlobalMiddlewareList() as $middleware) {
            $GLOBALS["log"]->debug("middle",[$middleware]);
            $slim->add($middleware);
        }
    }
```
Log:
```
[2023-05-30 12:59:55] DEBUG: middle [{"Espo\\Tools\\Api\\Cors\\Middleware":[]}] 
[2023-05-30 12:59:55] ERROR: 405 Method Not Allowed Type: Slim\Exception\HttpMethodNotAllowedException Code: 405 Message: Method not allowed. Must be one of: GET, POST, PUT, DELETE File: /var/www/crm/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php Line: 79 Trace: #0 /var/www/crm/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(44): Slim\Middleware\RoutingMiddleware->performRouting() #1 /var/www/crm/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process() #2 /var/www/crm/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle() #3 /var/www/crm/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process() #4 /var/www/crm/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle() #5 /var/www/crm/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle() #6 /var/www/crm/vendor/slim/slim/Slim/App.php(183): Slim\App->handle() #7 /var/www/crm/application/Espo/Core/Api/Starter.php(96): Slim\App->run() #8 /var/www/crm/application/Espo/Core/ApplicationRunners/Api.php(45): Espo\Core\Api\Starter->start() #9 /var/www/crm/application/Espo/Core/Application/RunnerRunner.php(87): Espo\Core\ApplicationRunners\Api->run() #10 /var/www/crm/application/Espo/Core/Application.php(78): Espo\Core\Application\RunnerRunner->run() #11 /var/www/crm/public/api/v1/index.php(37): Espo\Core\Application->run() #12 {main} Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.  
```

Any advice would be greatly appreciated. I would really like to test this feature for you.

**Comment by yurikuzn** [comment]
I forgot about routes. You also need to add API routes that will handle requests. I added an example to the PR description.

**Comment by bandtank** [comment]
There is a possibility that no route will handle OPTIONS. Sometimes the client wants to know if OPTIONS is supported without hitting an edpoint. Would you suggest creating a route specifically to handle this case? I'm not sure what to do.

**Comment by yurikuzn** [comment]
If the endpoint is the always the same, an empty route should work. Empty routes are supported as of recently.

**Comment by fhirter** [comment]
Can this be used in the default api?

**Comment by bandtank** [comment]
What do you mean by "default API"? Do you mean the existing routes that are already available in the application? If so, yes, you can add the middleware to every API endpoint or only some API endpoints.

**Comment by fhirter** [comment]
I am trying to access the endpoint `GET /api/v1/Account`.

I added the following to `data/config.php`:

```php
  'apiCorsAllowedOriginList' => [
    0 => 'https://example.com'
  ],
  'apiCorsAllowedMethodList' => [
    0 => 'GET',
    1 => 'OPTIONS'
  ],
  'apiCorsAllowedHeaderList' => [
    0 => 'Content-Type',
    1 => 'Accept',
    2 => 'X-Api-Key'
  ],
```

I was not able to set the cors headers doing this.

**Comment by yurikuzn** [comment]
Did you add the middleware to *globalMiddlewareClassNameList*?

You also need to add a route for the "OPTIONS" request, as stated in the issue description.

**Comment by fhirter** [comment]
No, I did not. I am not developing for EspoCRM. It would be nice to be able to enable CORS middleware from the UI or config.php. Would this be a new feature request?

**Comment by yurikuzn** [comment]
>  Where do I edit globalMiddlewareClassNameList?

You can find an example in this topic.

**Pull request merged**
