### PR TITLE
feature: notification sound

### PR DESCRIPTION
**Pull request by eymen-elkum**
Hi Yuri,

I wonder if you are interest of rerunning this feature, it was very nice and many clients may love it.

### CODE REVIEW

**Comment by yurikuzn** [comment]
Need to test first. Currently I have too much of work.

**Comment by eymen-elkum** [comment]
For sure!

I will rebase it on the master branch now ...

**Comment by yurikuzn** [comment]
All new features it's better to push to `master` branch. Unfortunately, after I changed the base it added unwanted changes.

**Comment by eymen-elkum** [comment]
fixed the unwanted changes

**Comment by yurikuzn** [comment]
How browsers behave? Does they ask a permission to play a sound?

**Comment by eymen-elkum** [comment]
In chrome everything is ok, but in safari not worked because of permission

**Comment by Kharg** [comment]
Where should I place the .mp3 file?

**Comment by Kharg** [comment]
@yurikuzn any chance of adding the option in the notification layout for future versions? :)

**Pull request closed without merging**
