### PR TITLE
Portal add application name parameter

### PR DESCRIPTION
**Pull request by eymen-elkum**
This make it possible to set custom app name to portals.

### CODE REVIEW

**Comment by yurikuzn** [comment]
Looks good.

**Comment by yurikuzn** [comment]
I can't get it to work.

**Comment by yurikuzn** [comment]
I reverted  this PR. I shouldn't have hurried to merge without checking.

PRs, others than small fixes, should contain more details in description. It's not clear what was the purpose of this feature. Either I don't understand or understand but the feature is not tested.

**Comment by yurikuzn** [comment]
I figured out what was missing. 

https://github.com/espocrm/espocrm/commit/e8cf54cfb87d325534baad28b4da59ffe06501ad#diff-7da4c6d80a753e08573420fbb6f4604f3e9318248578664d980db31584424b2cR43

**Comment by eymen-elkum** [comment]
Sorry because my email notification was not working, yes it seems I forgot to include the Portal entity line🤦🏻‍♂️

**Pull request merged**
