### PR TITLE
Improve french translation: Campaign.json + MassEmail.json

### PR DESCRIPTION
**Pull request by sebdoido**
Improve french translation: Campaign.json + MassEmail.json

I checked on POEditor
https://poeditor.com/projects/po_edit?id_language=50&id=58283

but all keys were not able to be updated there :-( 

Let me know if this PR is suitable for you or if we should update in POEditor first to avoid to loose any changes?

### CODE REVIEW

**Comment by yurikuzn** [comment]
Not sure. I think if you are going to make changes on POEditor it would be better to do only there and then I will import changes.

**Comment by sebdoido** [comment]
Ok, thanks for your feedback.
But currently, i cannot edit through this page
https://poeditor.com/projects/po_edit?id_language=50&id=58283 (french
translation)
all the keys

ex:
```
-    "campaignLogRecords": "Enregistrer",
+    "campaignLogRecords": "Logs",
```

I don't find how to create new entry. Maybe it's only for admin ?

**Comment by yurikuzn** [comment]
I've just imported new terms to poeditor. Can you please check if you have them available?

**Comment by yurikuzn** [comment]
I've also imported changes from POEditor to master branch.

Not sure why you can not edit on po editor. Have you added yourself as a contributor to French language?

**Comment by sebdoido** [comment]
Thanks, i have updated some fields in POEditor directly.

Now, the following keys are missing in POEditor

```
CampaignLogRecord -> presetFilters -> optedOut
MassMail -> fields -> startAt
MassMail -> fields -> replyToAddress
MassMail -> links -> emailTemplate
```

Could you add them ?
Thanks

**Comment by yurikuzn** [comment]
I've imported all labels. You can find them searching by:
Date Start
Reply-to Address
Email Template

**Comment by sebdoido** [comment]
Ok, that's ok for me now.
I updated in POEditor the different keys.
Could you import them in master or in this PR + merge ? :-)

Thanks!

**Comment by sebdoido** [comment]
(and i updated `Opt-Out Entirely`). Thanks for importing my changes :)

**Comment by yurikuzn** [comment]
I have to do a lot of operations to import labels from po to here. I will do it later.

**Comment by sebdoido** [comment]
Let me know if i can help to automate that part (through a makefile or something like that.. if it's time consuming).

I think there is an API to automate the export of all languages.

**Comment by yurikuzn** [comment]
It's automated enough.
1. Export po from poeditor.
2. Place exported file into build directory `build/espocrm-fr_FR.po`.
3. Run `node fr_FR`.
4. Files will be generated in build directory. You need to copy them to root directory and commit changes.

**Comment by sebdoido** [comment]
Thanks :)

All good, POEditor updated and all json files generated through `node lang.js fr_FR`

**Comment by sebdoido** [comment]
I rebase my branch with your origin/master branch.
It should be merged without any issues.

Thanks :)

**Comment by yurikuzn** [comment]
Thanks.

**Pull request merged**
