### PR TITLE
parseEmailToMarkdown function added for stream email posts

### PR DESCRIPTION
**Pull request by Sloff**
This improves the look and feel of emails within the stream

### CODE REVIEW

**Comment by yurikuzn** [comment]
Hi,

I can't apply this commit. I'm not sure whether this will function reliably.

**Comment by Sloff** [comment]
Would it change your mind if I add several unit tests for the function?

**Comment by Sloff** [comment]
Or I could simply provide a couple of example emails and how they appear in the stream

**Comment by Sloff** [comment]
There is also a composer package that can accomplish this: https://packagist.org/packages/league/html-to-markdown

**Comment by yurikuzn** [comment]
I don't have time now. I will leave it aside for the future.

**Pull request closed without merging**
