### PR TITLE
htmlizer `trTag` avoid breakline

### PR DESCRIPTION
**Pull request by eymen-elkum**
Hope this is useful PR.

links:

https://sourceforge.net/p/tcpdf/discussion/435311/thread/ff6879d2/

### CODE REVIEW

**Comment by yurikuzn** [comment]
After I moved all TCPDF logic behind and interface, having TCPDF specific parameters before that interface is not good.

**Comment by eymen-elkum** [comment]
Is there any woraround to make this work for TCPDF?

**Comment by yurikuzn** [comment]
I'm not sure how would be better. 

Does the browser strip this `nobr` attribute when you put it in wysiwyg?

**Comment by rabiibrahimi** [comment]
This is a very good PR. i have faced issues with this and would be great to solve this out. 
Thanks

**Pull request closed without merging**
