### PR TITLE
fix foreign enum & array with optionPath & translations

### PR DESCRIPTION
**Pull request by eymen-elkum**
Hi Yuri,

This is an issue when you create a foreign field for enum, array or multiple enum fields with optionsPath or translation set on field defs directly as path.
I hope it is useful

### CODE REVIEW

**Comment by yurikuzn** [comment]
Hi,

Fix is fine. The only thing needed, is that we need to clone translations with `Espo.Utils.clone(...)`  before assigning it to something.

**Comment by eymen-elkum** [comment]
I left your part as it is, so you use clone if found it needed

**Comment by yurikuzn** [comment]
I meant cloning translations Object. I will do after merge.

**Comment by yurikuzn** [comment]
I confused translation with translatedOptions. But you did right that you cloned options.

**Pull request merged**
