### PR TITLE
code improvements

### PR DESCRIPTION
**Pull request by eymen-elkum**

### CODE REVIEW

**Comment by yurikuzn** [comment]
I avoid direct usage of parameter values in class names. From my perspective, it's not an improvement. It would be an implicit support of custom parameter value which is not documented/officially supported. Maybe there's another way to achieve what you need.

**Comment by arkadiyasuratov** [comment]
Just throwing my two cents, but I prefer the original version. Sure, it's somewhat verbose, but I find it more readable.

**Comment by eymen-elkum** [comment]
I see, it is hard to get one vision on such topics :)

But was good to hear your comments for future's contributions.

**Comment by yurikuzn** [comment]
Having explicit class names is also useful to be able to find it in codebase.

**Pull request closed without merging**
